baseurl = "https://www.maicongouveia.com" # Hostname (and path) to the root.
title = "Maicon Gouveia" # Site title.
theme = "coder-portfolio" # Set the theme.
languagecode = "pt-BR" # The site’s language code used to generate RSS.
defaultcontentlanguage = "pt-BR" # The default content language.

paginate = 20 # Default number of pages per page in pagination.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # new add

[params] # theme parameters
    author = "Maicon Gouveia" # Author's name.
    info = "Developer" # Author's job title or info.
    description = "Saiba mais um pouco sobre Maicon" # Site description.
    keywords = "blog,developer,personal" # Site keywords.
    avatarurl = "/images/avatar.jpg" # Contain the path of the optionnal avatar in the static folder.

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = false
    hideCopyright = false

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    snsShare = false # new add

    thumbnail = "images/tn.png" # default sns thumbnail

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/maicongouveia/"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/gouveiaMaicon/"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/gouveiamaicon/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "posts"
[[menu.main]]
    name = "Sobre"
    weight = 2
    url = "sobre"